### ISSUE TITLE
Als functioneel beheerder wil ik een vergelijking tussen een aantal open source process engines,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/VoorzieningZGWnieuw#3]
zodat er een afweging gemaakt kan worden door de supply manager en product owner. 

In de vergelijking willen we rekening houden met
- gebruiksvriendelijkheid, onderhoudbaarheid, visualisatie
- ecosysteem (community, ondersteuning, prijs)
- welke talen worden ondersteund 
- API compliency 

- [ ] gartner report process engine
- [ ] met lazo afstemmen welke mogelijkheden er  zijn

**Comment by MichelleDautzenberg** [comment]
Eerste indruk Flowable:

-	Eenvoudig met docker te starten. 
-	Het is opgebouwd uit vier modules: modeler, task, identitymanagement en apps. 
-	De Apps module is handig omdat je daarin definieert welke processen bij elkaar horen en daar een soort losse taakapplicatie van maakt. 
-	Modeleren in de modeler gaat goed, maar is lastiger dan in Camunda (klikt wat minder makkelijk bij elkaar).
-	Formulieren bouwer is simpel, ik verwacht niet dat we dit richting de burger gaan gebruiken. Intern misschien ook niet.
-	Importeren van een proces uit Camunda modeler lijkt in eerste instantie goed te gaan. Het model wordt overgenomen en een aantal condities worden meegenomen. Echter bij het uitvoeren ervan krijg ik toch errors over de gezette condities. Ook al is kijk naar de taal van de condities, lijkt hier een afwijking in te zitten (flowable gebruikt $ en Camunda gebruikt #)

**Comment by JurjenBert** [comment]
niet meer relevant op dit moment
