### ISSUE TITLE
Als functioneel beheerder wil ik de bestaande componenten toetsen aan het metadatamodel,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/VoorzieningZGWnieuw#4]
zodat we kunnen vaststellen wat onze technische oplossing voldoet aan het metamodel. 

Dit doen we in twee stappen:
- [x] demo met Arno en functioneel beheer (13 dec) 
- [x] met Arno invulbaar model maken voor implementatie processen (verplicht, generiek, vanuit waar gevuld)

**Comment by MichelleDautzenberg** [comment]
Op 13 december heb ik met Arno alle componenten doorgenomen en naast het informatiemodel gehouden. Ik heb ook een account voor hem aangemaakt in OpenZaak. Arno kan hier mee verder. Ik heb input hieruit gekregen voor de benodigde codebibliotheek.

**Comment by MichelleDautzenberg** [comment]
Arno heeft inmiddels zijn vergelijking opgeleverd. Daaruit blijkt dat Gemeentezaak voldoet aan het informatiemodel van Utrecht. Het enige waar we rekening mee moeten houden is dat er in Utrecht geen gebruik wordt gemaakt van deelzaken, terwijl dit in Gemeentezaak wel mogelijk is.

Ik heb daarnaast een invulbaar format gemaakt voor de zaaktype inrichting. Dit kan bij de ketenanalyse worden ingevuld door de business/procesteam. Wij gebruiken dit dan om de zaaktypeinrichting in Gemeentezaak te doen.
