### ISSUE TITLE
Als functioneel beheerder wil ik een overzicht van onderwerpen die ontbreken in het informatiemodel,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/VoorzieningZGWnieuw#7]
zodat we later uit kunnen zoeken. 

Voorbeelden zijn onderwerpen als record management en autorisatie.

**Comment by MichelleDautzenberg** [comment]
**Functionele principes**
Taakapplicaties vs generieke applicaties vs kopieën van generieke applicaties
Autorisatiebeheer (in taakapplicatie, in generieke applicaties)
Recordmanagement
Modeleerprincipes

**Technische principes**
Autorisatiebeheer (app2app), doelbinding
Logging (applicatie en NLX)
Gebruik van meerdere ZTC, ZRC, DRC
Enkelvoudige vs meervoudige documentopslag
Dossiergericht werken
Welke procesengine
Architectuur 

**Design over (bestaande) componenten**
Verplicht gebruik van componenten? 
Wanneer afwijken van landelijke standaard of generieke componenten?
Migratiestrategie
Bestaande voorziening vs nieuwe voorziening

**Comment by MichelleDautzenberg** [comment]
Nog iemand toevoegingen?
