### ISSUE TITLE
Als functionel beheerder wil ik eenzelfde BPMN proces in drie verschillende process engines kunnen draaien,

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/VoorzieningZGWnieuw#9]
zodat ik de verschillende process enigines kan vergelijken en een keuze kan maken voor de meest geschikte. 

Ik wil in ieder geval Activiti, Camunda en jBPMN kunnen vergelijken. 
Ik wil een DMN tabel kunnen integreren. 
Ik wil inzicht krijgen in de mogelijkheden om UI te bouwen.
Ik wil inzicht krijgen in aspecten als bruikbaarheid, benoidigde kennis van programmeertalen als java, ondersteuning, verschillen tussen enterprise en community edition.

**Comment by MichelleDautzenberg** [comment]
We hebben dit in Camunda en Activiti gedaan en we hebben de verschillen in beeld. 
Deze worden meegenomen in de memo behorende bij #3
